name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: test-linux
    - run: |
        if [ ! -f "${{ steps.test-linux.outputs.archive }}" ]; then
          echo "${{ steps.test-linux.outputs.archive }} does not exist"
          exit 1
        fi
      shell: bash

  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: test-macos
    - run: |
        if [ ! -f "${{ steps.test-macos.outputs.archive }}" ]; then
          echo "${{ steps.test-macos.outputs.archive }} does not exist"
          exit 1
        fi
      shell: bash

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: Copy-Item "LICENSE" -Destination "LICENSE.exe"
      shell: powershell
    - uses: ./
      id: test-windows
    - run: |
        if (!(Test-Path "${{ steps.test-windows.outputs.archive }}")) {
          Write-Warning ""${{ steps.test-windows.outputs.archive }}" does not exist"
          exit 1
        }
      shell: powershell

  test-and-release:
    needs:
      - linux
      - macos
      - windows
    runs-on: macos-13
    steps:
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-macos-x64.zip
        key: LICENSE-macos-x64.zip-${{ github.sha }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-windows-x64.zip
        key: LICENSE-windows-x64.zip-${{ github.sha }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - run: |
        if [ ! -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-macos-x64.zip" ]; then
          echo "LICENSE-macos-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-windows-x64.zip" ]; then
          echo "LICENSE-windows-x64.zip does not exist"
          exit 1
        fi
      shell: bash
    - uses: prantlf/delete-cache-action@v3
      with:
        key: LICENSE-linux-x64.zip-${{ github.sha }}
    - uses: prantlf/delete-cache-action@v3
      with:
        key: LICENSE-macos-x64.zip-${{ github.sha }}
    - uses: prantlf/delete-cache-action@v3
      with:
        key: LICENSE-windows-x64.zip-${{ github.sha }}
    - uses: actions/checkout@v4
    - uses: prantlf/publish-release-action@v1
      if: ${{ github.ref_name == 'master' }}
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
